[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "https://siteanswer-web-three.vercel.app"
additional_redirect_urls = ["http://localhost:3000/auth/callback", "https://siteanswer-web-three.vercel.app/auth/callback"]

[auth.email]
enable_signup = true
enable_confirmations = true
